# Generated by Django 5.0.7 on 2024-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomsBooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='images',
        ),
        migrations.AddField(
            model_name='rooms',
            name='view',
            field=models.CharField(default='Sea', max_length=100),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='number',
            field=models.IntegerField(),
        ),
    ]
