# Generated by Django 5.0.7 on 2024-08-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomsBooking', '0003_userregistration_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='number',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='view',
        ),
        migrations.AddField(
            model_name='rooms',
            name='bath_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='bed_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(default='Economy', max_length=50),
        ),
    ]
