# Generated by Django 5.0.7 on 2024-08-18 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomsBooking', '0004_remove_rooms_number_remove_rooms_view_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('avaliable', models.BooleanField(default=True)),
                ('room_type', models.CharField(default='Economy', max_length=50)),
                ('bed_count', models.IntegerField(blank=True, null=True)),
                ('bath_count', models.IntegerField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, default='.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RoomsBooking.room'),
        ),
        migrations.DeleteModel(
            name='rooms',
        ),
    ]
