# Generated by Django 5.0.7 on 2024-08-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomsBooking', '0005_room_alter_userregistration_room_delete_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='room-1.jpg', null=True, upload_to='room_pics'),
        ),
    ]
