# Generated by Django 5.0.7 on 2024-08-21 12:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomsBooking', '0006_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='enddate',
            field=models.DateTimeField(help_text='Enter the date of purchase', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)], verbose_name='Check out date'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='startdate',
            field=models.DateTimeField(help_text='Enter the date of purchase', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)], verbose_name='Check in date'),
        ),
    ]
