# Generated by Django 5.0.7 on 2024-08-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomsBooking', '0008_alter_userregistration_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
