# Generated by Django 5.0.7 on 2024-09-17 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomsBooking', '0009_alter_userregistration_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='startdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
